### PR TITLE
Added links to other utilities

### PR DESCRIPTION
**Pull request by bradvogel**

### CODE REVIEW

**Comment by bradvogel** [comment]
Ping @alexeypetrushin

**Comment by bradvogel** [comment]
ping @alexeypetrushin

**Comment by alexeypetrushin** [comment]
Hi @bradvogel I granted you permission to contribute to this repo, and bumped the version to 2.

Sorry for delay.

**Comment by bradvogel** [comment]
Much appreciated, thanks!

**Pull request merged**
