### PR TITLE
enrich errors call stack

### PR DESCRIPTION
**Pull request by mihaislobozeanu**
Hi,

I've made some changes to get a more relevant call stack on error.

Thanks.

### CODE REVIEW

**Comment by mihaislobozeanu** [comment]
I have the latest mocha version and locally this error is not raised.

**Comment by d3m3vilurr** [comment]
Ok. I checked this pr (our company also want this pr ;) )
`mocha` was all passed on local machine, but travis still [failed][1].
so, patched pr code, like this https://github.com/d3m3vilurr/synchronize/commit/0c04d258dda0
after patch, test all [passed][2].

@mihaislobozeanu can you merge this patch?

[1]: https://travis-ci.org/d3m3vilurr/synchronize/builds/95747499
[2]: https://travis-ci.org/d3m3vilurr/synchronize/builds/95749496

**Comment by d3m3vilurr** [comment]
ah...wait my patch really cause leak problem. :'(

**Comment by d3m3vilurr** [comment]
Sorry messages. This is final fix https://github.com/d3m3vilurr/synchronize/commit/e132c9918 :)

**Comment by mihaislobozeanu** [comment]
Done, thanks.
One question. Why it was a memory leak?

**Comment by d3m3vilurr** [comment]
1. original pr not have leak. but basically, this variable is global variable. (not have `let` or `var` keyword). so, this patch will give wrong result.

2. my first patch have real leak. `node` process cannot detect in `fiber` object is same `Fiber.current`, it cause c++ module(`node-fibers` implements, `Fiber.current` will return `GetCurrent()` result. so it will have not same address). so we can't pass outside variable to `fiber.run` closure, it will cause that variables not mark `GC` target(yes, it's insane.). 

3. but, logically `fiber` variable is same `Fiber.current`. so we can use this context to pass variable.

#32 help about this problem.

**Comment by alexeypetrushin** [comment]
Hi guys, sorry for delay, didn't had much free time recently.

@d3m3vilurr I added you to contributors, if you wish please feel free to merge this PR. I also bumped the version to 2 for the new development. (v1 will be kept frozen, only for backward compatible fixes).

**Comment by d3m3vilurr** [comment]
thx invite :)
btw i think this pr is not enough. so i will add more patch at tomorrow.

**Comment by d3m3vilurr** [comment]
close this pr. we will handle #49

**Comment by d3m3vilurr** [comment]
merged a42337bd6d

**Pull request closed without merging**
